# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FacebookAppPermissions' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!
  # Pods for FacebookAppPermissions
pod 'FBSDKCoreKit'
pod 'FBSDKShareKit'
pod 'FBSDKLoginKit'

pod 'iOSDFULibrary', '~> 4.0'
pod 'EVReflection', '~> 5.0'
pod 'SWRevealViewController', '~> 2.3'
pod 'CorePlot', '~> 2.2'

end
